/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfaces;

import com.mycompany.model.Student;
import com.mycompany.model.StudentDAO;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vankh
 */
public class StudentListView extends javax.swing.JFrame {

    /**
     * Creates new form StudentListView
     */
    private long UID = 1;
    private String [] columnNames = new String [] {
        "ID", "Họ Tên", "Ngày Sinh", "Địa Chỉ", "Khoa", "Lớp","GPA"};
    private Object data = new Object[][]{};
    
    public StudentListView() {
        initComponents();
        ListSinhVienTable.setComponentPopupMenu(studentPopupMenu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogAddStudent = new javax.swing.JDialog();
        DialogPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtKhoa = new javax.swing.JTextField();
        txtLop = new javax.swing.JTextField();
        txtGPA = new javax.swing.JTextField();
        btnAddSV = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        jMenuItem1 = new javax.swing.JMenuItem();
        SortbuttonGroup = new javax.swing.ButtonGroup();
        studentPopupMenu = new javax.swing.JPopupMenu();
        MenuItemUpdate = new javax.swing.JMenuItem();
        MenuItemDelete = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListSinhVienTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        SinhVienMenu = new javax.swing.JMenu();
        AddStudentMenuItem = new javax.swing.JMenuItem();
        SortMenu = new javax.swing.JMenu();
        rbtnMenuitemNone = new javax.swing.JRadioButtonMenuItem();
        rbtnMenuItemSortGPA = new javax.swing.JRadioButtonMenuItem();
        rbtnMenuItemSortName = new javax.swing.JRadioButtonMenuItem();
        NhanVienMenu = new javax.swing.JMenu();

        DialogAddStudent.setTitle("Thêm Sinh Viên");
        DialogAddStudent.setBackground(new java.awt.Color(204, 204, 255));
        DialogAddStudent.setBounds(new java.awt.Rectangle(100, 100, 430, 400));
        DialogAddStudent.setModal(true);

        DialogPanel.setBackground(new java.awt.Color(204, 204, 255));
        DialogPanel.setToolTipText("01");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Thêm Sinh Viên");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("ID :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Họ Tên :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Ngày Sinh :");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Địa Chỉ :");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Khoa :");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Lớp :");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("GPA :");

        txtHoTen.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtNgaySinh.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtDiaChi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtKhoa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtLop.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtGPA.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        btnAddSV.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAddSV.setText("Thêm");
        btnAddSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSVActionPerformed(evt);
            }
        });

        btnHuy.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        txtID.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout DialogPanelLayout = new javax.swing.GroupLayout(DialogPanel);
        DialogPanel.setLayout(DialogPanelLayout);
        DialogPanelLayout.setHorizontalGroup(
            DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(DialogPanelLayout.createSequentialGroup()
                        .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHoTen)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtKhoa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLop, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtGPA, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDiaChi)
                            .addGroup(DialogPanelLayout.createSequentialGroup()
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogPanelLayout.createSequentialGroup()
                        .addGap(0, 276, Short.MAX_VALUE)
                        .addComponent(btnHuy)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddSV)))
                .addContainerGap())
        );
        DialogPanelLayout.setVerticalGroup(
            DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DialogPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 62, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddSV)
                            .addComponent(btnHuy))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout DialogAddStudentLayout = new javax.swing.GroupLayout(DialogAddStudent.getContentPane());
        DialogAddStudent.getContentPane().setLayout(DialogAddStudentLayout);
        DialogAddStudentLayout.setHorizontalGroup(
            DialogAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DialogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogAddStudentLayout.setVerticalGroup(
            DialogAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DialogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        MenuItemUpdate.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        MenuItemUpdate.setText("Cập Nhật");
        studentPopupMenu.add(MenuItemUpdate);

        MenuItemDelete.setText("Xóa");
        MenuItemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemDeleteActionPerformed(evt);
            }
        });
        studentPopupMenu.add(MenuItemDelete);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FrameSinhVien");

        txtTimKiem.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        btnTimKiem.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        ListSinhVienTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ListSinhVienTable.setModel(new DefaultTableModel((Object[][]) data, columnNames));
        jScrollPane1.setViewportView(ListSinhVienTable);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh Sách Sinh Viên");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTimKiem)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        SinhVienMenu.setText("Sinh Viên");

        AddStudentMenuItem.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        AddStudentMenuItem.setText("Thêm Sinh Viên");
        AddStudentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentMenuItemActionPerformed(evt);
            }
        });
        SinhVienMenu.add(AddStudentMenuItem);

        SortMenu.setText("Sắp Xếp");

        SortbuttonGroup.add(rbtnMenuitemNone);
        rbtnMenuitemNone.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rbtnMenuitemNone.setSelected(true);
        rbtnMenuitemNone.setText("None");
        SortMenu.add(rbtnMenuitemNone);

        SortbuttonGroup.add(rbtnMenuItemSortGPA);
        rbtnMenuItemSortGPA.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rbtnMenuItemSortGPA.setText("Theo GPA");
        rbtnMenuItemSortGPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMenuItemSortGPAActionPerformed(evt);
            }
        });
        SortMenu.add(rbtnMenuItemSortGPA);

        SortbuttonGroup.add(rbtnMenuItemSortName);
        rbtnMenuItemSortName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rbtnMenuItemSortName.setText("Theo Tên");
        rbtnMenuItemSortName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMenuItemSortNameActionPerformed(evt);
            }
        });
        SortMenu.add(rbtnMenuItemSortName);

        SinhVienMenu.add(SortMenu);

        jMenuBar1.add(SinhVienMenu);

        NhanVienMenu.setText("Nhân Viên");
        jMenuBar1.add(NhanVienMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void HienDialog(){
        DialogAddStudent.setVisible(true);
    }
    
    public void TatDialog(){
        DialogAddStudent.setVisible(false);
    }
    
    private void btnAddSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSVActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_btnAddSVActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void AddStudentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddStudentMenuItemActionPerformed

    private void rbtnMenuItemSortGPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMenuItemSortGPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMenuItemSortGPAActionPerformed

    private void rbtnMenuItemSortNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMenuItemSortNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMenuItemSortNameActionPerformed

    private void MenuItemDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemDeleteActionPerformed

    public boolean checkRbtnSortByName(){
        if(rbtnMenuItemSortName.isSelected()){
            return true;
        }else
            return false;
    }
    
    public boolean checkRbtnSortByGPA(){
        if(rbtnMenuItemSortGPA.isSelected()){
            return true;
        }else
            return false;
    }
    
    public void addMenuItemDelete(ActionListener listener){
        MenuItemDelete.addActionListener(listener);
    }
    
    public void addSortByName(ActionListener listener){
        rbtnMenuItemSortName.addActionListener(listener);
    }
    
    public void addSortByGPA(ActionListener listener){
        rbtnMenuItemSortGPA.addActionListener(listener);
    }
    
    public void addStudentMenuItemListener(ActionListener listener){
        AddStudentMenuItem.addActionListener(listener);
    }
    public void addTimKiemListener(ActionListener listener){
        btnTimKiem.addActionListener(listener);
    }
    
    public String ThongTinTim(){
        return txtTimKiem.getText().trim();
    }
    
    public void addBtnHuyListener(ActionListener listener){
        btnHuy.addActionListener(listener);
    }
    
    public void addAddSinhVienDialogListener(ActionListener listener){
        btnAddSV.addActionListener(listener);
    }
    
    
    /**
     * @param args the command line arguments
     */
    
    public void ShowMessage(String message){
        JOptionPane.showMessageDialog(this, message);
    }
    
    public void showListStudents(List<Student> list) {
        int size = list.size();
        Object [][] students = new Object[size][7];
        for (int i = 0; i < size; i++) {
            students[i][0] = list.get(i).getId();
            students[i][1] = list.get(i).getHoTen();
            students[i][2] = list.get(i).getNgaySinh();
            students[i][3] = list.get(i).getDiaChi();
            students[i][4] = list.get(i).getKhoa();
            students[i][5] = list.get(i).getLop();
            students[i][6] = list.get(i).getGPA();
        }
    ListSinhVienTable.setModel(new DefaultTableModel(students, columnNames));
    }
    
    private boolean validateName() {
        String name = txtHoTen.getText();
        if (name == null || "".equals(name.trim())) {
            txtHoTen.requestFocus();
            ShowMessage("Name không được trống.");
            return false;
        }
        return true;
    }
    
    private boolean validateNgaySinh() {
        String ngaySinh = txtNgaySinh.getText();
        if (ngaySinh == null || "".equals(ngaySinh.trim())) {
            txtNgaySinh.requestFocus();
            ShowMessage("Name không được trống.");
            return false;
        }
        return true;
    }

    private boolean validateDiaChi() {
        String diaChi = txtDiaChi.getText();
        if (diaChi == null || "".equals(diaChi.trim())) {
            txtDiaChi.requestFocus();
            ShowMessage("Name không được trống.");
            return false;
        }
        return true;
    }
    
    private boolean validateKhoa() {
        String khoa = txtKhoa.getText();
        if (khoa == null || "".equals(khoa.trim())) {
            txtKhoa.requestFocus();
            ShowMessage("Name không được trống.");
            return false;
        }
        return true;
    }
    
    private boolean validateLop() {
        String lop = txtLop.getText();
        if (lop == null || "".equals(lop.trim())) {
            txtLop.requestFocus();
            ShowMessage("Name không được trống.");
            return false;
        }
        return true;
    }
    
    private boolean validateGPA(){
        try{
            double GPA = Double.parseDouble(txtGPA.getText().trim());
            if(GPA < 0 || GPA > 10){
                txtGPA.requestFocus();
                ShowMessage("GPA Không Hợp Lệ!");
                return false;
            }
        }catch(Exception e){
            txtGPA.requestFocus();
            ShowMessage("GPA Không Hợp Lệ!");
            return false;
        }
        return true;
    }
    

    public Student SetStudentInfo(){
        Student student = new Student();
        if(!validateName() || !validateNgaySinh() || ! validateDiaChi() || !validateLop() || !validateKhoa() || !validateGPA()){
            return null;
        }
        try {
            if(txtID.getText() != null && !"".equals(txtID.getText()))
            {
                student.setId(Long.parseLong(txtID.getText()));
            }
            student.setHoTen(txtHoTen.getText().trim());
            student.setNgaySinh(txtNgaySinh.getText().trim());
            student.setDiaChi(txtDiaChi.getText().trim());
            student.setKhoa(txtKhoa.getText().trim());
            student.setLop(txtLop.getText().trim());
            student.setGPA(Double.parseDouble(txtGPA.getText().trim()));
            return student;
        } catch (Exception e) {
            ShowMessage(e.getMessage());
        }
        return null;
    }
    
    public void ClearText(){
        txtID.setText("");
        txtHoTen.setText("");
        txtNgaySinh.setText("");
        txtDiaChi.setText("");
        txtKhoa.setText("");
        txtLop.setText("");
        txtGPA.setText("");
    }
    
    public String getUID(){
        int row = ListSinhVienTable.getSelectedRow();
        return ListSinhVienTable.getModel().getValueAt(row, 0).toString();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddStudentMenuItem;
    private javax.swing.JDialog DialogAddStudent;
    private javax.swing.JPanel DialogPanel;
    private javax.swing.JTable ListSinhVienTable;
    private javax.swing.JMenuItem MenuItemDelete;
    private javax.swing.JMenuItem MenuItemUpdate;
    private javax.swing.JMenu NhanVienMenu;
    private javax.swing.JMenu SinhVienMenu;
    private javax.swing.JMenu SortMenu;
    private javax.swing.ButtonGroup SortbuttonGroup;
    private javax.swing.JButton btnAddSV;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButtonMenuItem rbtnMenuItemSortGPA;
    private javax.swing.JRadioButtonMenuItem rbtnMenuItemSortName;
    private javax.swing.JRadioButtonMenuItem rbtnMenuitemNone;
    private javax.swing.JPopupMenu studentPopupMenu;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtGPA;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtKhoa;
    private javax.swing.JTextField txtLop;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
