/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfaces;

import com.mycompany.model.Student;
import java.awt.event.ActionListener;
import java.sql.Struct;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vankh
 */
public class StudentListView extends javax.swing.JFrame {

    /**
     * Creates new form StudentListView
     */
    private Student student;
    private String [] columnNames = new String [] {
        "ID", "Họ Tên", "Ngày Sinh", "Địa Chỉ", "Khoa", "Lớp","GPA"};
    private Object data = new Object[][]{};
    
    public StudentListView() {
        initComponents();
        ListSinhVienTable.setComponentPopupMenu(studentPopupMenu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogStudentManager = new javax.swing.JDialog();
        DialogPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtKhoa = new javax.swing.JTextField();
        txtLop = new javax.swing.JTextField();
        txtGPA = new javax.swing.JTextField();
        btnAddSV = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        txtPhoneNumber = new javax.swing.JTextField();
        txtGmail = new javax.swing.JTextField();
        txtID = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        SortbuttonGroup = new javax.swing.ButtonGroup();
        studentPopupMenu = new javax.swing.JPopupMenu();
        MenuItemUpdate = new javax.swing.JMenuItem();
        MenuItemDelete = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListSinhVienTable = new javax.swing.JTable();
        lbTitle = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        StudentMenu = new javax.swing.JMenu();
        AddStudentMenuItem = new javax.swing.JMenuItem();
        SortMenu = new javax.swing.JMenu();
        rbtnMenuitemNone = new javax.swing.JRadioButtonMenuItem();
        rbtnMenuItemSortGPA = new javax.swing.JRadioButtonMenuItem();
        rbtnMenuItemSortName = new javax.swing.JRadioButtonMenuItem();
        UserMenu = new javax.swing.JMenu();

        DialogStudentManager.setTitle("Thêm Sinh Viên");
        DialogStudentManager.setBackground(new java.awt.Color(204, 204, 255));
        DialogStudentManager.setBounds(new java.awt.Rectangle(100, 100, 500, 450));
        DialogStudentManager.setModal(true);

        DialogPanel.setBackground(new java.awt.Color(153, 153, 255));
        DialogPanel.setToolTipText("01");
        DialogPanel.setMinimumSize(new java.awt.Dimension(500, 500));
        DialogPanel.setName(""); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Quản Lí Sinh Viên");

        txtHoTen.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtHoTen.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Full Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        txtNgaySinh.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtNgaySinh.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Date of Birth", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        txtDiaChi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtDiaChi.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        txtKhoa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtKhoa.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Department", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        txtLop.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtLop.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Class", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        txtGPA.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtGPA.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GPA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        btnAddSV.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAddSV.setText("Add");
        btnAddSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSVActionPerformed(evt);
            }
        });

        btnHuy.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnHuy.setText("Cancel");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        txtPhoneNumber.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtPhoneNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Phone Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        txtGmail.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtGmail.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Gmail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        txtID.setBackground(new java.awt.Color(204, 204, 204));
        txtID.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "UID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DialogPanelLayout = new javax.swing.GroupLayout(DialogPanel);
        DialogPanel.setLayout(DialogPanelLayout);
        DialogPanelLayout.setHorizontalGroup(
            DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHoTen)
                    .addGroup(DialogPanelLayout.createSequentialGroup()
                        .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDiaChi))
                    .addComponent(txtGPA)
                    .addGroup(DialogPanelLayout.createSequentialGroup()
                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGmail, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                    .addGroup(DialogPanelLayout.createSequentialGroup()
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(DialogPanelLayout.createSequentialGroup()
                        .addComponent(txtKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLop))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnHuy)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddSV)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)))
                .addContainerGap())
        );
        DialogPanelLayout.setVerticalGroup(
            DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy)
                    .addComponent(btnAddSV)
                    .addComponent(btnUpdate))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        btnUpdate.setEnabled(false);

        javax.swing.GroupLayout DialogStudentManagerLayout = new javax.swing.GroupLayout(DialogStudentManager.getContentPane());
        DialogStudentManager.getContentPane().setLayout(DialogStudentManagerLayout);
        DialogStudentManagerLayout.setHorizontalGroup(
            DialogStudentManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DialogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogStudentManagerLayout.setVerticalGroup(
            DialogStudentManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DialogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MenuItemUpdate.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        MenuItemUpdate.setText("Update");
        MenuItemUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemUpdateActionPerformed(evt);
            }
        });
        studentPopupMenu.add(MenuItemUpdate);

        MenuItemDelete.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        MenuItemDelete.setText("Delete");
        MenuItemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemDeleteActionPerformed(evt);
            }
        });
        studentPopupMenu.add(MenuItemDelete);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FrameSinhVien");

        txtTimKiem.setBackground(new java.awt.Color(204, 255, 204));
        txtTimKiem.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtTimKiem.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N

        btnTimKiem.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        ListSinhVienTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 51), new java.awt.Color(153, 255, 255), new java.awt.Color(255, 204, 204), new java.awt.Color(204, 204, 255)));
        ListSinhVienTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ListSinhVienTable.setModel(new DefaultTableModel((Object[][]) data, columnNames));
        jScrollPane1.setViewportView(ListSinhVienTable);

        lbTitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Student List");
        lbTitle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTimKiem))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        StudentMenu.setText("Student");
        StudentMenu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        AddStudentMenuItem.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        AddStudentMenuItem.setText("Thêm Sinh Viên");
        AddStudentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentMenuItemActionPerformed(evt);
            }
        });
        StudentMenu.add(AddStudentMenuItem);

        SortMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        SortMenu.setText("Sắp Xếp");
        SortMenu.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        SortbuttonGroup.add(rbtnMenuitemNone);
        rbtnMenuitemNone.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rbtnMenuitemNone.setSelected(true);
        rbtnMenuitemNone.setText("None");
        SortMenu.add(rbtnMenuitemNone);

        SortbuttonGroup.add(rbtnMenuItemSortGPA);
        rbtnMenuItemSortGPA.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rbtnMenuItemSortGPA.setText("Theo GPA");
        rbtnMenuItemSortGPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMenuItemSortGPAActionPerformed(evt);
            }
        });
        SortMenu.add(rbtnMenuItemSortGPA);

        SortbuttonGroup.add(rbtnMenuItemSortName);
        rbtnMenuItemSortName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rbtnMenuItemSortName.setText("Theo Tên");
        rbtnMenuItemSortName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMenuItemSortNameActionPerformed(evt);
            }
        });
        SortMenu.add(rbtnMenuItemSortName);

        StudentMenu.add(SortMenu);

        jMenuBar1.add(StudentMenu);

        UserMenu.setText("User");
        UserMenu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuBar1.add(UserMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ShowDialog(){
        btnAddSV.setEnabled(true);
        btnUpdate.setEnabled(false);
        DialogStudentManager.setVisible(true);
    }
    
    public void HideDialog(){
        DialogStudentManager.setVisible(false);
    }
    
    private void btnAddSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSVActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_btnAddSVActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void AddStudentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddStudentMenuItemActionPerformed

    private void rbtnMenuItemSortGPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMenuItemSortGPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMenuItemSortGPAActionPerformed

    private void rbtnMenuItemSortNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMenuItemSortNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMenuItemSortNameActionPerformed

    private void MenuItemDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void MenuItemUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemUpdateActionPerformed

    public void addMenuItemUpdate(ActionListener listener){
        MenuItemUpdate.addActionListener(listener);
    }
    
    public void addbtnUpdate(ActionListener listener){
        btnUpdate.addActionListener(listener);
    }
    
    public boolean checkRbtnSortByName(){
        if(rbtnMenuItemSortName.isSelected()){
            return true;
        }else
            return false;
    }
    
    public boolean checkRbtnSortByGPA(){
        if(rbtnMenuItemSortGPA.isSelected()){
            return true;
        }else
            return false;
    }
    
    public void addMenuItemDelete(ActionListener listener){
        MenuItemDelete.addActionListener(listener);
    }
    
    public void addSortByName(ActionListener listener){
        rbtnMenuItemSortName.addActionListener(listener);
    }
    
    public void addSortByGPA(ActionListener listener){
        rbtnMenuItemSortGPA.addActionListener(listener);
    }
    
    public void addStudentMenuItemListener(ActionListener listener){
        AddStudentMenuItem.addActionListener(listener);
    }
    public void addTimKiemListener(ActionListener listener){
        btnTimKiem.addActionListener(listener);
    }
    
    public String ThongTinTim(){
        return txtTimKiem.getText().trim();
    }
    
    public void addBtnHuyListener(ActionListener listener){
        btnHuy.addActionListener(listener);
    }
    
    public void addAddSinhVienDialogListener(ActionListener listener){
        btnAddSV.addActionListener(listener);
    }
    
    
    /**
     * @param args the command line arguments
     */
    
    public void ShowMessage(String message){
        JOptionPane.showMessageDialog(this, message);
    }
    
    public void showListStudents(List<Student> list) {
        int size = list.size();
        Object [][] students = new Object[size][7];
        for (int i = 0; i < size; i++) {
            students[i][0] = list.get(i).getId();
            students[i][1] = list.get(i).getName();
            students[i][2] = list.get(i).getDateOfBirth();
            students[i][3] = list.get(i).getAddress();
            students[i][4] = list.get(i).getDepartment();
            students[i][5] = list.get(i).getclass();
            students[i][6] = list.get(i).getGPA();
        }
    ListSinhVienTable.setModel(new DefaultTableModel(students, columnNames));
    }
    
    public boolean checkPhoneNumber(String str){
        // Bieu thuc chinh quy mo ta dinh dang so dien thoai
        String reg = "^(0|\\+84)(\\s|\\.)?((3[2-9])|(5[689])|(7[06-9])|(8[1-689])|(9[0-46-9]))(\\d)(\\s|\\.)?(\\d{3})(\\s|\\.)?(\\d{3})$";
        // Kiem tra dinh dang
        boolean kt = str.matches(reg);
        if (kt == false) {
            return  false ;
        } else {
            return  true ;
        }
    }
    
    public boolean checkEmail(String str){
        // Bieu thuc chinh quy mo ta dinh dang email
        String regexPattern = "^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@"
                + "[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";

        return Pattern.compile(regexPattern)
                .matcher(str)
                .matches();
        
    }
    
    private boolean ValidatePhoneNumber(){
        String phoneNumber = txtPhoneNumber.getText().toString().trim();
        if(phoneNumber == null || "".equals(phoneNumber.trim())){
            txtPhoneNumber.requestFocus();
            ShowMessage("Phone Number không được trống.");
            return false;
        }else if(!checkPhoneNumber(phoneNumber)){
            txtPhoneNumber.requestFocus();
            ShowMessage("Phone Number không đúng định dạng.");
            return false;
        }
        return true;
    }
    
    private boolean ValidateEmail(){
        String Email = txtGmail.getText().toString().trim();
        if(Email == null || "".equals(Email.trim())){
            txtGmail.requestFocus();
            ShowMessage("Email không được trống.");
            return false;
        }
        else if(!checkEmail(Email)){
            txtGmail.requestFocus();
            ShowMessage("Email không đúng định dạng.");
            return false;
        }
        return true;
    }
    
    private boolean validateName() {
        String name = txtHoTen.getText();
        if (name == null || "".equals(name.trim())) {
            txtHoTen.requestFocus();
            ShowMessage("Name không được trống.");
            return false;
        }
        return true;
    }
    
    private boolean validateBirthday() {
        String ngaySinh = txtNgaySinh.getText();
        if (ngaySinh == null || "".equals(ngaySinh.trim())) {
            txtNgaySinh.requestFocus();
            ShowMessage("Name không được trống.");
            return false;
        }
        return true;
    }

    private boolean validateAddress() {
        String diaChi = txtDiaChi.getText();
        if (diaChi == null || "".equals(diaChi.trim())) {
            txtDiaChi.requestFocus();
            ShowMessage("Name không được trống.");
            return false;
        }
        return true;
    }
    
    private boolean validateDepartment() {
        String khoa = txtKhoa.getText();
        if (khoa == null || "".equals(khoa.trim())) {
            txtKhoa.requestFocus();
            ShowMessage("Name không được trống.");
            return false;
        }
        return true;
    }
    
    private boolean validateclass() {
        String lop = txtLop.getText();
        if (lop == null || "".equals(lop.trim())) {
            txtLop.requestFocus();
            ShowMessage("Name không được trống.");
            return false;
        }
        return true;
    }
    
    private boolean validateGPA(){
        try{
            double GPA = Double.parseDouble(txtGPA.getText().trim());
            if(GPA < 0 || GPA > 10){
                txtGPA.requestFocus();
                ShowMessage("GPA Không Hợp Lệ!");
                return false;
            }
        }catch(Exception e){
            txtGPA.requestFocus();
            ShowMessage("GPA Không Hợp Lệ!");
            return false;
        }
        return true;
    }
    
    public void getID(){
        student = new Student();
        txtID.setText(String.valueOf(student.getId()));
    }

    public Student SetStudentInfo(){
        if(!validateName() || !validateBirthday()|| ! validateAddress()|| !validateclass()|| !validateDepartment()|| !validateGPA() || !ValidatePhoneNumber() || !ValidateEmail()){
            return null;
        }
        try {
            student.setName(txtHoTen.getText().trim());
            student.setDateOfBirth(txtNgaySinh.getText().trim());
            student.setAddress(txtDiaChi.getText().trim());
            student.setDepartment(txtKhoa.getText().trim());
            student.setClass(txtLop.getText().trim());
            student.setGPA(Double.parseDouble(txtGPA.getText().trim()));
            student.setPhoneNumber(txtPhoneNumber.getText().trim());
            student.setEmail(txtGmail.getText().trim());
            return student;
        } catch (Exception e) {
            ShowMessage(e.getMessage());
        }
        return null;
    }
    
    public void ClearText(){
        txtID.setText("");
        txtHoTen.setText("");
        txtNgaySinh.setText("");
        txtDiaChi.setText("");
        txtKhoa.setText("");
        txtLop.setText("");
        txtGPA.setText("");
        txtGmail.setText("");
        txtPhoneNumber.setText("");
    }
    
    public String getUID(){
        int row = ListSinhVienTable.getSelectedRow();
        return ListSinhVienTable.getModel().getValueAt(row, 0).toString();
    }
    
    public void ShowDialogUpdate(Student s){
        txtID.setText(String.valueOf(s.getId()));
        txtHoTen.setText(s.getName());
        txtNgaySinh.setText(s.getDateOfBirth());
        txtDiaChi.setText(s.getAddress());
        txtKhoa.setText(s.getDepartment());
        txtLop.setText(s.getclass());
        txtGPA.setText(String.valueOf(s.getGPA()));
        txtGmail.setText(s.getEmail());
        txtPhoneNumber.setText(s.getPhoneNumber());
        btnAddSV.setEnabled(false);
        btnUpdate.setEnabled(true);
        DialogStudentManager.setVisible(true);
    }
    
    public void UpdateStudent(Student s){
        if(!validateName() || !validateBirthday()|| ! validateAddress()|| !validateclass()|| !validateDepartment()|| !validateGPA() || !ValidatePhoneNumber() || !ValidateEmail()){
            return ;
        }
        try {
            s.setName(txtHoTen.getText().trim());
            s.setDateOfBirth(txtNgaySinh.getText().trim());
            s.setAddress(txtDiaChi.getText().trim());
            s.setDepartment(txtKhoa.getText().trim());
            s.setClass(txtLop.getText().trim());
            s.setGPA(Double.parseDouble(txtGPA.getText().trim()));
            s.setPhoneNumber(txtPhoneNumber.getText().trim());
            s.setEmail(txtGmail.getText().trim());
        } catch (Exception e) {
            ShowMessage(e.getMessage());
        }
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddStudentMenuItem;
    private javax.swing.JPanel DialogPanel;
    private javax.swing.JDialog DialogStudentManager;
    private javax.swing.JTable ListSinhVienTable;
    private javax.swing.JMenuItem MenuItemDelete;
    private javax.swing.JMenuItem MenuItemUpdate;
    private javax.swing.JMenu SortMenu;
    private javax.swing.ButtonGroup SortbuttonGroup;
    private javax.swing.JMenu StudentMenu;
    private javax.swing.JMenu UserMenu;
    private javax.swing.JButton btnAddSV;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JRadioButtonMenuItem rbtnMenuItemSortGPA;
    private javax.swing.JRadioButtonMenuItem rbtnMenuItemSortName;
    private javax.swing.JRadioButtonMenuItem rbtnMenuitemNone;
    private javax.swing.JPopupMenu studentPopupMenu;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtGPA;
    private javax.swing.JTextField txtGmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JLabel txtID;
    private javax.swing.JTextField txtKhoa;
    private javax.swing.JTextField txtLop;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
